### ISSUE TITLE
Multiple SG2 segments not allowed

### ISSUE THREAD

**Issue by szocsbarni** [php-edifact/edifact#130]
Given the below, short edi content, ```D01B``` version, ```pricat``` type:
```
UNA:+.?'
UNB+UNOC:3+0000000000000:14+0000000000000:14+231126:1830+502+0000++++PRICAT'
UNH+1+PRICAT:D:01B:UN:EAN009'
BGM+9:::PREISLISTE+11+4'
DTM+137:20231126:102'
NAD+BY+1111111111111::9'
NAD+SU+2222222222222::9'
UNT+0+1'
UNZ+1+502'
```

the current code version on the master (d4c8450f7091b748c3857e9d2d4c297f5be93397) skips the 2nd ```NAD``` command with the below warning:
```
Array
(
    [0] => Array
        (
            [text] => The message has some additional segments beyond the maximum repetition allowed (skipped)
            [position] => 4
            [segmentId] => NAD
        )

)
```

while the release v1 (29498658298fa9df8d9fe5763bfd7353ec3b6658), parses them, without any warnings. According to the PRICAT [documentation](http://www.stylusstudio.com/edifact/D01B/PRICAT.htm), there can be multiple ```SG2``` segments, containing only one ```NAD``` command.

**Comment by sabas** [comment]
You are right..
You can mantain the segment disabling the patching ```$interpreter->togglePatching(false);```
The problem lies here
https://github.com/php-edifact/edifact/blob/master/src/EDI/Interpreter.php#L660
The issue is that the code doesn't check currently if the first element of the next group is the same.

**Comment by sabas** [comment]
@szocsbarni  I pushed a commit which should deal with this case, can you test with a larger sample? Thanks :)

**Comment by szocsbarni** [comment]
@sabas the fix is ok, parsing does not stop on the double ```NAD``` command and processes larger files. I am still getting a warning though, will it be eliminated? 
```
Array
(
    [0] => Array
        (
            [text] => The message has some additional segments beyond the maximum repetition allowed (skipped)
            [position] => 4
            [segmentId] => NAD
        )

)
```

**Comment by szocsbarni** [comment]
yes, even running this concrete code segment of yours (replaced function calls of ```d()``` to ```print_r()```). Below is my full output:

```
Array
(
    [0] => Array
        (
            [0] => UNB
            [1] => Array
                (
                    [0] => UNOC
                    [1] => 3
                )

            [2] => Array
                (
                    [0] => 0000000000000
                    [1] => 14
                )

            [3] => Array
                (
                    [0] => 0000000000000
                    [1] => 14
                )

            [4] => Array
                (
                    [0] => 231126
                    [1] => 1830
                )

            [5] => 502
            [6] => 0000
            [7] =>
            [8] =>
            [9] =>
            [10] => PRICAT'
        )

    [1] => Array
        (
            [0] => UNH
            [1] => 1
            [2] => Array
                (
                    [0] => PRICAT
                    [1] => D
                    [2] => 01B
                    [3] => UN
                    [4] => EAN009'
                )

        )

    [2] => Array
        (
            [0] => BGM
            [1] => Array
                (
                    [0] => 9
                    [1] =>
                    [2] =>
                    [3] => PREISLISTE
                )

            [2] => 11
            [3] => 4'
        )

    [3] => Array
        (
            [0] => DTM
            [1] => Array
                (
                    [0] => 137
                    [1] => 20231126
                    [2] => 102'
                )

        )

    [4] => Array
        (
            [0] => NAD
            [1] => BY
            [2] => Array
                (
                    [0] => 1111111111111
                    [1] =>
                    [2] => 9'
                )

        )

    [5] => Array
        (
            [0] => NAD
            [1] => SU
            [2] => Array
                (
                    [0] => 2222222222222
                    [1] =>
                    [2] => 9'
                )

        )

    [6] => Array
        (
            [0] => UNT
            [1] => 0
            [2] => 1'
        )

    [7] => Array
        (
            [0] => UNZ
            [1] => 1
            [2] => 502'
        )

)
Array
(
)
Array
(
    [0] => Array
        (
            [messageHeader] => Array
                (
                    [segmentIdx] => 0
                    [segmentCode] => UNH
                    [segmentGroup] =>
                    [messageReferenceNumber] => 1
                    [messageIdentifier] => Array
                        (
                            [messageType] => PRICAT
                            [messageVersionNumber] => D
                            [messageReleaseNumber] => 01B
                            [controllingAgency] => UN
                            [associationAssignedCode] => EAN009'
                        )

                )

            [beginningOfMessage] => Array
                (
                    [segmentIdx] => 1
                    [segmentCode] => BGM
                    [segmentGroup] =>
                    [document] => Array
                        (
                            [documentNameCode] => 9
                            [codeListIdentificationCode] =>
                            [codeListResponsibleAgencyCode] =>
                            [documentName] => PREISLISTE
                        )

                    [document1] => Array
                        (
                            [documentIdentifier] => 11
                        )

                    [messageFunctionCode] => 4'
                )

            [dateOrtimeOrperiod] => Array
                (
                    [segmentIdx] => 2
                    [segmentCode] => DTM
                    [segmentGroup] =>
                    [date] => Array
                        (
                            [dateOrTimeOrPeriodFunctionCodeQualifier] => 137
                            [dateOrTimeOrPeriodValue] => 20231126
                            [dateOrTimeOrPeriodFormatCode] => 102'
                        )

                )

            [SG2] => Array
                (
                    [0] => Array
                        (
                            [nameAndAddress] => Array
                                (
                                    [segmentIdx] => 3
                                    [segmentCode] => NAD
                                    [segmentGroup] => SG2
                                    [partyFunctionCodeQualifier] => BY
                                    [partyIdentificationDetails] => Array
                                        (
                                            [partyIdentifier] => 1111111111111
                                            [codeListIdentificationCode] =>
                                            [codeListResponsibleAgencyCode] => 9'
                                        )

                                )

                        )

                )

            [messageTrailer] => Array
                (
                    [segmentIdx] => 5
                    [segmentCode] => UNT
                    [segmentGroup] => SG2
                    [numberOfSegmentsInTheMessage] => 0
                    [messageReferenceNumber] => 1'
                )

        )

)
Array
(
    [0] => Array
        (
            [text] => The message has some additional segments beyond the maximum repetition allowed (skipped)
            [position] => 4
            [segmentId] => NAD
        )

)

```

**Comment by szocsbarni** [comment]
Can I help you anything with this issue? @sabas

**Comment by sabas** [comment]
With the commit https://github.com/php-edifact/edifact/commit/dffa0937c49c6404ae8ebe303996c3f4018dbe08 in the test case you provided it seemed fixed.
Do you replicate it with the same test or with another file? If it's private you can share by email..

**Comment by szocsbarni** [comment]
yes, that commit indeed solves it, my fault, sorry!
